# Generated by Django 3.0.5 on 2020-04-22 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutorePostModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='admin', max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='blogpostmodel',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
        migrations.AlterField(
            model_name='blogpostmodel',
            name='titolo',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='blogpostmodel',
            name='autore',
            field=models.ForeignKey(default='admin', on_delete=django.db.models.deletion.CASCADE, related_name='autore', to='blog.AutorePostModel'),
        ),
    ]
