# Generated by Django 3.0.5 on 2020-05-08 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogcommentmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcommentmodel',
            name='punti',
            field=models.SmallIntegerField(default=1),
        ),
    ]
