# Generated by Django 3.0.5 on 2020-04-22 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200422_2216'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpostmodel',
            options={},
        ),
        migrations.AlterField(
            model_name='blogpostmodel',
            name='autore',
            field=models.CharField(default='admin', max_length=20),
        ),
        migrations.DeleteModel(
            name='AutorePostModel',
        ),
    ]
