# Generated by Django 3.0.5 on 2020-04-22 22:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_blogpostmodel_autore'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostmodel',
            name='autore',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
